- name: Restart podman socket
  ansible.builtin.systemd:
    name: podman.socket
    state: restarted
    daemon_reload: true

- name: Restart github runner
  ansible.builtin.systemd:
    name: "actions.runner.{{ github_runner_owner }}-{{ github_runner_repo }}.{{ github_runner_name }}.service"
    state: restarted
  failed_when: false
