ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/terraform_homelab
ansible_python_interpreter: /usr/bin/python3

docker_compose_dir: /opt/docker
nas_puid: 0
nas_pgid: 0
wordpress_version: "6.9.4"
timezone: "America/Montreal"
traefik_acme_email: "patrick@drifterapps.com"
pbs_domain: "pbs.moreaulab.ca"
proxmox_domain: "pve.moreaulab.ca"
proxmox_node: "homelab"
