ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/terraform_homelab
ansible_python_interpreter: /usr/bin/python3

docker_compose_dir: /opt/docker
nas_puid: 0
nas_pgid: 0
timezone: 'America/Montreal'
traefik_acme_email: 'patrick@drifterapps.com'
pbs_domain: 'pbs.moreaulab.ca'
proxmox_domain: 'pve.moreaulab.ca'
proxmox_node: 'homelab'

pbs_prune_schedule: 'daily'
pbs_gc_schedule: 'daily'
pbs_prune_keep_last: 7
pbs_prune_keep_daily: 14
pbs_prune_keep_weekly: 8
pbs_prune_keep_monthly: 6
