- name: Deploy via Docker Compose
  ansible.builtin.include_tasks: docker.yaml
  when: container_runtime == 'docker'

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
  when: container_runtime == 'podman'
