services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    ports:
      - 8096:8096
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin-http.rule=Host(`jellyfin.homelab.lan`)
      - traefik.http.routers.jellyfin-http.entrypoints=web
      - traefik.http.routers.jellyfin-http.priority=100
      - traefik.http.services.jellyfin-http.loadbalancer.server.port=8096
      - kop.bind.ip=${HOST}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl=jellyfin.homelab.lan
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas-docker-data/home-vm/jellyfin/config:/config
      - /mnt/nas-media:/data/movies:ro
    restart: unless-stopped
