services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /mnt/nas-docker-data/traefik-configs:/etc/traefik/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`gateway.homelab.lan`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
    environment:
      - TZ=${TZ}

networks:
  proxy:
