- name: Create directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/cloudflare"
    state: directory
    mode: "0755"

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
