services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /mnt/nas-docker-data/traefik-configs:/etc/traefik/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gateway.homelab.lan`)"
      - "traefik.http.routers.gateway.service=api@internal"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.priority=100"

      - "traefik.http.middlewares.force-https.redirectscheme.scheme=https"

      - "traefik.http.routers.global-redirect.rule=!HostRegexp(`homelab\\.lan`)"
      - "traefik.http.routers.global-redirect.entrypoints=web"
      - "traefik.http.routers.global-redirect.middlewares=force-https"
      - "traefik.http.routers.global-redirect.service=noop@internal"
      - "traefik.http.routers.global-redirect.priority=1"
    environment:
      - TZ=${TZ}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: traefik-redis
    restart: unless-stopped
    ports:
      - 6379:6379
