services:
  traefik-kop:
    image: ghcr.io/jittering/traefik-kop:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - BIND_IP=${BIND_IP}

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami-home.rule=Host(`whoami-home.homelab.lan`)
      - traefik.http.routers.whoami-home.entrypoints=websecure
      - traefik.http.routers.whoami-home.tls=true
      - traefik.http.routers.whoami-home.tls.certresolver=acme_certresolver
      - traefik.http.services.whoami-home.loadbalancer.server.port=80
      - traefik.http.services.whoami-home.loadbalancer.server.scheme=http
      - kop.bind.ip=${BIND_IP}

include:
  - path: calibre-web/docker-compose.yml
  - path: file-browser/docker-compose.yml
  - path: homepage/docker-compose.yml
  - path: jellyfin/docker-compose.yml
  - path: portainer/docker-compose.yml
  - path: service-watcher/docker-compose.yml
  - path: transmission/docker-compose.yml
