- name: Create folder
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/calibre"
    state: directory
    mode: "0755"

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nas_puid }}"
    group: "{{ nas_pgid }}"
    mode: "0777"
  loop:
    - /data/calibre

- name: Copy docker-compose.yaml
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_compose_dir }}/calibre/docker-compose.yaml"
    mode: "0644"

- name: Copy .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_compose_dir }}/calibre/.env"
    mode: "0600"

- name: Copy kepubify folder
  ansible.builtin.copy:
    src: kepubify/
    dest: "{{ docker_compose_dir }}/calibre/kepubify"
    mode: "0755"

- name: Start
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}/calibre"
    state: present
