- name: Create folder
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/vaultwarden"
    state: directory
    mode: "0755"

- name: Create volume folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  loop:
    - /data/vaultwarden
    - /data/vaultwarden/data
    - /data/vaultwarden/mariadb

- name: Deploy via Docker Compose
  ansible.builtin.include_tasks: docker.yaml
  when: container_runtime == 'docker'

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
  when: container_runtime == 'podman'
