services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.18
    container_name: filebrowser
    user: ${PUID}:${PGID}
    ports:
      - 8080:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /data/filebrowser/config:/config
      - /data/filebrowser/data:/srv
      - /data/filebrowser/database:/database
      - /media:/srv/nas-media
    restart: unless-stopped
