- name: Create directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/homepage"
    state: directory
    mode: "0755"

- name: Create config directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/homepage/config"
    state: directory
    mode: "0755"

- name: Create logs directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/homepage/config/logs"
    state: directory
    mode: "0755"

- name: Copy config files
  ansible.builtin.copy:
    src: config/
    dest: "{{ docker_compose_dir }}/homepage/config/"
    owner: "{{ nas_puid }}"
    group: "{{ nas_pgid }}"
    mode: "0644"

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
