services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.26
    container_name: calibre-web
    ports:
      - 8083:8083
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas-docker-data/home-vm/calibre/config:/config
      - /mnt/nas-books:/books
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre-http.rule=Host(`books.homelab.lan`)
      - traefik.http.routers.calibre-http.entrypoints=web
      - traefik.http.routers.calibre-http.priority=100
      - traefik.http.services.calibre-http.loadbalancer.server.port=8083
      - kop.bind.ip=${HOST}
    restart: unless-stopped
