- name: Create directory
  ansible.builtin.file:
    path: '{{ docker_compose_dir }}/jellyfin'
    state: directory
    mode: '0755'

- name: Create data directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ nas_puid }}'
    group: '{{ nas_pgid }}'
    mode: '0755'
  loop:
    - /data/jellyfin
    - '{{ docker_compose_dir }}/jellyfin/config/cache'
    - '{{ docker_compose_dir }}/jellyfin/config/log'
    - '{{ docker_compose_dir }}/jellyfin/config/transcodes'

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
