services:
  traefik:
    image: traefik:v3.7.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8443:8443
      - 8080:8080
    networks:
      - gateway
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./conf.d:/etc/traefik/conf.d:ro
      - ./acme.json:/etc/traefik/acme.json
      - certs:/etc/traefik/certs

  certs-dumper:
    image: ldez/traefik-certs-dumper:v2.11.4
    container_name: traefik-certs-dumper
    restart: unless-stopped
    environment:
      - PVE_API_TOKEN=${PVE_API_TOKEN}
    volumes:
      - ./acme.json:/etc/traefik/acme.json:ro
      - certs:/etc/traefik/certs
      - ./certs-dumper-key:/root/.ssh/deploy_key:ro

volumes:
  certs:

networks:
  gateway:
    external: true
