- name: Create folder
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/filebrowser"
    state: directory
    mode: "0755"

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nas_puid }}"
    group: "{{ nas_pgid }}"
    mode: "0777"
  loop:
    - /data/filebrowser
    - /data/filebrowser/config
    - /data/filebrowser/data
    - /data/filebrowser/database

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
