- name: Create directory
  ansible.builtin.file:
    path: '{{ docker_compose_dir }}/blackbox_exporter'
    state: directory
    mode: '0755'

- name: Copy blackbox config
  ansible.builtin.template:
    src: blackbox.yml.j2
    dest: '{{ docker_compose_dir }}/blackbox_exporter/blackbox.yml'
    mode: '0644'

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
