- name: Create directory
  ansible.builtin.file:
    path: '{{ docker_compose_dir }}/prometheus'
    state: directory
    mode: '0755'

- name: Create config directory
  ansible.builtin.file:
    path: '{{ docker_compose_dir }}/prometheus/config'
    state: directory
    mode: '0755'

- name: Copy prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: '{{ docker_compose_dir }}/prometheus/config/prometheus.yml'
    mode: '0644'
  notify: Reload prometheus config

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
