- name: Deploy Proxmox Backup Server
  hosts: lxc-pbs
  roles:
    - proxmox-backup-server

- name: Provision all LXC
  hosts: lxc:!lxc-pbs
  roles:
    - docker
    - node_exporter
    - cadvisor

- name: Deploy Gateway
  hosts: lxc-gateway
  roles:
    - traefik
    - cloudflare

- name: Deploy Media
  hosts: lxc-media
  roles:
    - calibre
    - jellyfin
    - transmission
    - filebrowser
    - service-watcher
    - proxmox-backup-client

- name: Deploy Essere
  hosts: lxc-essere
  roles:
    - essere
    - proxmox-backup-client

- name: Deploy Monitoring
  hosts: lxc-monitoring
  roles:
    - prometheus
    - loki
    - grafana
    - pve_exporter
    - proxmox-backup-client

- name: Deploy Tools
  hosts: lxc-tools
  roles:
    - homepage

- name: Deploy Vault
  hosts: lxc-vault
  roles:
    - vaultwarden
    - proxmox-backup-client

- name: Deploy Immich
  hosts: lxc-immich
  roles:
    - immich
    - proxmox-backup-client

- name: Deploy Promtail
  hosts: lxc:!lxc-monitoring:!lxc-pbs
  roles:
    - promtail

- name: Deploy Home Assistant
  hosts: lxc-homeassistant
  roles:
    - homeassistant
    - proxmox-backup-client

- name: Deploy Ollama
  hosts: lxc-ollama
  roles:
    - ollama

- name: Deploy Open WebUI
  hosts: lxc-open-webui
  roles:
    - open-webui
    - proxmox-backup-client
