---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Media:
    - Jellyfin:
        - abbr: JF
          href: https://jellyfin.moreaulab.ca
    - Filebrowser:
        - abbr: FB
          href: https://filebrowser.moreaulab.ca
    - Book Orbit:
        - abbr: BO
          href: https://books.moreaulab.ca
    - Transmission:
        - abbr: TR
          href: https://transmission.moreaulab.ca

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
