---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- AI:
    - Claude:
        - abbr: CL
          href: https://claude.ai/
          icon: sh-claude
    - Gemini:
        - abbr: GG
          href: https://gemini.google.com/app
          icon: sh-google-gemini
    - ChatGPT:
        - abbr: CG
          href: https://chat.openai.com/
          icon: sh-chatgpt

- Finance:
    - Intuit QuickBooks:
        - abbr: QBO
          href: https://qbo.intuit.com/
    - Scotia Bank:
        - abbr: SB
          href: https://www.scotiaonline.scotiabank.com/?language=French
    - TD Bank:
        - abbr: TD
          href: https://authentication.td.com/uap-ui/?consumer=easyweb&locale=fr_CA#/uap/login
    - CIBC Bank:
        - abbr: CIBC
          href: https://www.cibc.com/fr/personal-banking.html
    - Desjardins:
        - abbr: DJ
          href: https://www.desjardins.com/qc/fr.html
    - Tangerine:
        - abbr: TG
          href: https://www.tangerine.ca/app/#/login/login-id?locale=fr_CA
    - Deneault & Robillard:
        - abbr: DR
          href: https://deneaultrobillard.cchifirm.ca/3/clientportal/#/login
    - Holefeeder:
        - abbr: HF
          href: https://holefeeder.drifterapps.app/

- Productivity:
    - iCloud:
        - abbr: IC
          href: https://www.icloud.com/
          icon: sh-icloud
    - Fastmail:
        - abbr: FM
          href: https://www.fastmail.com/
          icon: sh-fastmail
    - Google Mail:
        - abbr: GM
          href: https://mail.google.com/
          icon: sh-gmail

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
          icon: sh-github

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: sh-reddit

- Entertainment:
    - Netflix:
        - abbr: NF
          href: https://netflix.com/
          icon: sh-netflix
    - Disney+:
        - abbr: DP
          href: https://www.disneyplus.com/
          icon: sh-disney-plus
    - Crave:
        - abbr: CR
          href: https://www.crave.ca/
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: sh-youtube

- Arg:
    - Ocean of PDF:
        - abbr: OOP
          href: https://oceanofpdf.com/
    - The Pirate Bay:
        - abbr: TPB
          href: https://thepiratebay.org/
    - Anna's Archive:
        - abbr: AA
          href: https://annas-archive.gl/
