- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.moreaulab.ca
        description: Movies & TV Shows
        widget:
          type: jellyfin
          url: https://jellyfin.moreaulab.ca
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}

    - Books:
        icon: calibre-web.png
        href: https://books.moreaulab.ca
        description: E-book Library
        widget:
          type: calibreweb
          url: https://books.moreaulab.ca
          username: {{HOMEPAGE_VAR_CALIBREWEB_USERNAME}}
          password: {{HOMEPAGE_VAR_CALIBREWEB_PASSWORD}}

    - Transmission:
        icon: transmission.png
        href: https://transmission.moreaulab.ca
        description: Torrent Client
        widget:
          type: transmission
          url: https://transmission.moreaulab.ca
          rpcUrl: /transmission/
          username: {{HOMEPAGE_VAR_TRANSMISSION_USERNAME}}
          password: {{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}

    - Filebrowser:
        icon: filebrowser.png
        href: https://filebrowser.moreaulab.ca
        description: File Browser
        widget:
          type: filebrowser
          url: https://filebrowser.moreaulab.ca
          username: {{HOMEPAGE_VAR_FILEBROWSER_USERNAME}}
          password: {{HOMEPAGE_VAR_FILEBROWSER_PASSWORD}}
          # authHeader: X-My-Header # If using Proxy header authentication

- Docker:
    - Qnap Watcher:
        icon: qnap.png
        href: https://qnap.homelab.lan
        widget:
          type: customapi
          url: https://service-watcher.moreaulab.ca/api/qnap
          mappings:
            - field: Status
              label: Status
            - field: LastCheck
              label: Last Check
            - field: Progress
              label: Progress
            - field: FinishIn
              label: Finish In

- Infrastructure:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.homelab.lan:8006
        description: Virtual Machine Manager
        widget:
          type: proxmox
          url: https://proxmox.homelab.lan:8006
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          node: homelab

    - Traefik:
        icon: traefik.png
        href: https://gateway.moreaulab.ca
        description: Reverse Proxy
        widget:
          type: traefik
          url: https://gateway.moreaulab.ca

    - Qnap:
        icon: qnap.png
        href: https://qnap.homelab.lan
        ping: qnap.homelab.lan
        description: NAS Management
        widget:
          type: qnap
          url: https://qnap.homelab.lan:443
          username: {{HOMEPAGE_VAR_QNAP_USERNAME}}
          password: {{HOMEPAGE_VAR_QNAP_PASSWORD}}
          volume: DataVol1
          fields: ['cpuUsage', 'memUsage', 'systemTempC', 'volumeUsage']

- Self-Hosted:
    - Immich:
        icon: immich.png
        href: https://immich.moreaulab.ca
        description: Photo & Video Backup
        widget:
          type: immich
          url: https://immich.moreaulab.ca
          key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}
          fields: ['photos', 'videos', 'storage']
          version: 2

- Observability:
    - Grafana:
        icon: grafana.png
        href: https://grafana.moreaulab.ca
        description: Metrics Dashboard
        widget:
          type: grafana
          version: 2
          url: https://grafana.moreaulab.ca
          username: {{HOMEPAGE_VAR_GRAFANA_ADMIN_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_ADMIN_PASSWORD}}

    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.moreaulab.ca
        description: Metrics Server
        widget:
          type: prometheus
          url: https://prometheus.moreaulab.ca

- Security & Network:
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vault.moreaulab.ca
        ping: vault.moreaulab.ca
        description: Password Manager

    - Cloudflare:
        icon: cloudflare.png
        href: https://dash.cloudflare.com
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARE_API_KEY}}

    - Home Assistant:
        icon: homeassistant.png
        href: https://ha.moreaulab.ca
        widget:
          type: homeassistant
          url: https://ha.moreaulab.ca
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_API_KEY}}
          custom:
            - state: sensor.total_power
            - state: sensor.total_energy_today
              label: energy today
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
              label: switches on
            - state: weather.forecast_home
              label: wind speed
              value: '{attributes.wind_speed} {attributes.wind_speed_unit}'
