- name: Create directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/loki"
    state: directory
    mode: "0755"

- name: Copy config files
  ansible.builtin.copy:
    src: config/
    dest: "{{ docker_compose_dir }}/loki/config/"
    mode: "0644"

- name: Deploy via Podman Quadlet
  ansible.builtin.include_tasks: podman.yaml
