services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - 8080:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser-http.rule=Host(`filebrowser.homelab.lan`)
      - traefik.http.routers.filebrowser-http.entrypoints=web
      - traefik.http.routers.filebrowser-http.priority=100
      - traefik.http.services.filebrowser-http.loadbalancer.server.port=8080
      - kop.bind.ip=${HOST}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/nas-docker-data/filebrowser/data:/srv
      - /mnt/nas-docker-data/filebrowser/config:/config
      - /mnt/nas-docker-data/filebrowser/database:/database
      - /mnt/nas-books:/srv/nas-books
      - /mnt/nas-docker-data:/srv/nas-docker-data
      - /mnt/nas-media:/srv/nas-media
    restart: unless-stopped
