log:
  level: INFO

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false
  redis:
    endpoints:
      - "traefik-redis:6379"
    rootKey: "traefik"
  file:
    directory: /etc/traefik/conf.d
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  portainer-agent:
    address: ":8000"

certificatesResolvers:
  acme_certresolver:
    acme:
      email: patrick@drifterapps.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
